// middleware/authMiddleware.js

// ════════════════════════════════════════════════════
// SYSTEM DESIGN #2 — Role Based Access Control
// ════════════════════════════════════════════════════
// Access control works at TWO layers:
//
// LAYER 1 — This middleware (runs on every request)
//
//   Step 1: Frontend sends request with header:
//           Authorization: Bearer <firebase_token>
//
//   Step 2: verifyToken() extracts the token,
//           calls Firebase to verify it,
//           attaches decoded user to req.user
//           decoded = { uid, email, role, name }
//
//   Step 3: requireRole() checks req.user.role
//           against the allowed roles for that route.
//           If role doesn't match → 403 Access Denied
//           If role matches      → next() → controller runs
//
// LAYER 2 — Firestore Security Rules (firestore.rules)
//   Even if this middleware is bypassed somehow,
//   Firestore will still block the read/write
//   at the database level based on the same role.
//
// Role assignment flow:
//   Admin creates user → Firebase Auth account created
//   → custom claim set: { role: 'driver' | 'passenger' | 'admin' }
//   → custom claim is embedded in the JWT token
//   → verifyToken reads it from decoded token
//   → no extra database call needed for role check
//
// Role matrix:
//   Route prefix    Allowed roles
//   /auth           public (no role needed)
//   /driver/*       driver only
//   /passenger/*    passenger only
//   /payment/*      passenger (own) | admin (all)
//   /admin/*        admin only
//   /director/*     director only
// ════════════════════════════════════════════════════

const { firebaseAuth, firestoreDb } = require('../config/firebase')
const { SESSION_COOKIE_NAME } = require('../config/auth')


const getBearerToken = (req) => {
    const authHeader = req.headers.authorization

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return ''
    }

    return authHeader.split('Bearer ')[1]
}


const getSessionCookie = (req) => {
    return req.cookies?.[SESSION_COOKIE_NAME] || ''
}


const verifyToken = async (req, res, next) => {
    const bearerToken = getBearerToken(req)
    const sessionCookie = getSessionCookie(req)

    if (!bearerToken && !sessionCookie) {
        return res.status(401).json({
            error: 'Missing authorization token.'
        })
    }

    // Support legacy admin tokens (generated by director approve flow)
    // Format: ADM_{institutionId}_{uid}_{timestamp}_{random}
    if (bearerToken && bearerToken.startsWith('ADM_')) {
        try {
            const snap = await firestoreDb.collection('admins').where('adminToken', '==', bearerToken).limit(1).get();
            if (!snap.empty) {
                const doc = snap.docs[0];
                const adminData = doc.data();
                req.user = {
                    uid: adminData.uid || doc.id,
                    email: adminData.email || null,
                    role: 'admin',
                    name: adminData.name || null
                };
                req.authType = 'adminToken';
                return next();
            }
        } catch (err) {
            console.warn('[authMiddleware] adminToken lookup failed', err);
            // fallthrough to other checks
        }
    }

    if (bearerToken) {
        try {
            const decoded = await firebaseAuth.verifyIdToken(bearerToken)
            req.user = decoded
            req.authType = 'idToken'
            return next()
        } catch (error) {
            if (!sessionCookie) {
                if (error.code === 'auth/id-token-expired') {
                    return res.status(401).json({ error: 'Token expired. Please login again.' })
                }
                return res.status(401).json({ error: 'Invalid token.' })
            }
        }
    }

    try {
        const decoded = await firebaseAuth.verifySessionCookie(sessionCookie, true)
        req.user = decoded
        req.authType = 'sessionCookie'
        return next()
    } catch (error) {
        return res.status(401).json({ error: 'Invalid session.' })
    }
}


const requireRole = (...allowedRoles) => {
    return (req, res, next) => {
        const userRole = req.user?.role

        if (!userRole || !allowedRoles.includes(userRole)) {
            return res.status(403).json({
                error: `Access denied. Required: ${allowedRoles}. Your role: ${userRole}`
            })
        }
        next()
    }
}


const adminOnly     = [verifyToken, requireRole('admin')]
const directorOnly  = [verifyToken, requireRole('director')]
const driverOnly    = [verifyToken, requireRole('driver')]
const passengerOnly = [verifyToken, requireRole('passenger')]
const anyRole       = [verifyToken, requireRole('admin', 'director', 'driver', 'passenger')]


module.exports = {
    verifyToken,
    requireRole,
    adminOnly,
    directorOnly,
    driverOnly,
    passengerOnly,
    anyRole
}